const books = [
  {
    id: "001",
    author: "چینوا آچه‌به",
    country: "نیجریه",
    image: "1.png",
    language: "انگلیسی",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 209,
    title: "همه چیز فرو می‌پاشد",
    year: 1958,
  },
  {
    id: "002",
    author: "هانس کریستین آندرسن",
    country: "دانمارک",
    image: "2.png",
    language: "دانمارکی",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "داستان‌های افسانه‌ای",
    year: 1836,
  },
  {
    id: "003",
    author: "دانته آلیگیری",
    country: "ایتالیا",
    image: "3.png",
    language: "ایتالیایی",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "کمدی الهی",
    year: 1315,
  },
  {
    id: "004",
    author: "مورین گالری کوواکس",
    country: "سومر و امپراتوری اکدی",
    image: "4.png",
    language: "آکدی",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 160,
    title: "حماسه گیلگمش",
    year: -1700,
  },
  {
    id: "005",
    author: "گراهام ریکاردو",
    country: "امپراتوری هخامنشی",
    image: "5.png",
    language: "عبری",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "کتاب ایوب",
    year: -600,
  },
  {
    id: "006",
    author: "حَنان الشیخ",
    country: "هند/ایران/عراق/مصر/تاجیکستان",
    image: "6.png",
    language: "عربی",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "هزار و یک شب",
    year: 1200,
  },
  {
    id: "007",
    author: "رابرت کوک",
    country: "ایسلند",
    image: "7.png",
    language: "انگلیسی",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    pages: 384,
    title: "حماسه نیال",
    year: 1350,
  },
  {
    id: "008",
    author: "جین آستن",
    country: "بریتانیا",
    image: "8.png",
    language: "انگلیسی",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 226,
    title: "غرور و تعصب",
    year: 1813,
  },
  {
    id: "009",
    author: "اونوره دو بالزاک",
    country: "فرانسه",
    image: "9.png",
    language: "فرانسوی",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    pages: 443,
    title: "پدر گوریو",
    year: 1835,
  },
  {
    id: "010",
    author: "ساموئل بکت",
    country: "جمهوری ایرلند",
    image: "10.png",
    language: "فرانسوی",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    pages: 256,
    title: "مولوی، مالون می‌میرد",
    year: 1952,
  },
];

export { books };
